### ISSUE TITLE
Configuration file extension cause crash (Traceback - KeyError: 'Interface' (ERROR 500))

### ISSUE THREAD

**Issue by jkumar2001** [donaldzou/wireguard-dashboard#27]
**Describe The Problem**
Flask comes up fine, but while trying to login recieve Error 500 on the browser and following Traceback

**Expected Error / Traceback**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "dashboard.py", line 501, in conf
    config_list = get_conf_list()
  File "dashboard.py", line 268, in get_conf_list
    temp = {"conf": i, "status": get_conf_status(i), "public_key": get_conf_pub_key(i)}
  File "dashboard.py", line 223, in get_conf_pub_key
    pri = conf.get("Interface", "PrivateKey")
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'Interface'
10.127.0.28 - - [03/Jul/2021 13:47:11] "GET //configuration/wg0 HTTP/1.1" 500 -
10.127.0.28 - - [03/Jul/2021 13:47:12] "GET /favicon.ico HTTP/1.1" 404 -
[2021-07-03 13:47:12,405] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'Interface'

```

**To Reproduce**
Please provide how you run the dashboard

**OS Information:**
 - OS: Ubuntu 18.04.5 LTS
 - Python Version: Python 3.6.9

**Sample of your `.conf` file**
```
cat wg-dashboard.ini 
[Account]
username = ######
password = ######

[Server]
wg_conf_path = /etc/wireguard
app_ip = 10.127.0.1
app_port = 10086
auth_req = true
version = v2.1
dashboard_refresh_interval = 15000

```

**Comment by donaldzou** [comment]
Hi, could you please provide a sample of your wireguard config file? for example your `wg0.conf`

**Comment by jkumar2001** [comment]
I think I found the cause of issue. I had an additional "valid" wireguard configuration named as `wg0.conf.old` in `/etc/wireguard`, once I removed the file, wgd daemon restarted, everything started working as expected.

I am still not sure why this would cause such an issue, even when the file name does not end with `.conf`. I would still consider this a bug, but please close if you think its not worth fixing.

**Comment by donaldzou** [comment]
I see, I will put this fix into the next version. Thank you for reporting this ;)
