### ISSUE TITLE
Key Error trying to get configuration

### ISSUE THREAD

**Issue by antonioag95** [donaldzou/wireguard-dashboard#3]
Hello, thank you for your quick update about adding custom peer names! 
I get a KeyError while trying to fetch configuration for my wg0 plus the homepage does not show all data I can see in your screenshots!
That's the error I can see:

```
[2021-04-03 10:21:58,655] ERROR in app: Exception on /get_config/wg0 [GET]
Traceback (most recent call last):
  File "/home/antonio/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/antonio/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/antonio/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/antonio/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/antonio/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/antonio/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "dashboard.py", line 210, in get_conf
    "peer_data":get_conf_peers_data(config_name),
  File "dashboard.py", line 122, in get_conf_peers_data
    peer_data[data_usage[count]]['allowed_ip'] = data_usage[count+1]
KeyError: '192.168.9.0/24'
```
I know it must be an error with my configuration file, if possible I would like to help, maybe we can talk on another platform instead of using GitHub, let me know and thank you again!

**Comment by donaldzou** [comment]
Hi, do you have discord?

**Comment by antonioag95** [comment]
Thank you for your answer. I do, how can I get in touch with you there?

**Comment by donaldzou** [comment]
Hi, you can search my account as The Manager#8971
