### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ben-dd** [donaldzou/wireguard-dashboard#35]
**Describe The Problem**
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Expected Error / Traceback**

Please provide the error traceback here
```
➜ ./wgd.sh debug
Starting Wireguard Dashboard in the foreground.
 * Serving Flask app "Wireguard Dashboard" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:10086/ (Press CTRL+C to quit)
User not loggedin - Attemped access: index
38.80.149.105 - - [02/Aug/2021 21:39:18] "GET / HTTP/1.1" 302 -
38.80.149.105 - - [02/Aug/2021 21:39:18] "GET /signin HTTP/1.1" 200 -
38.80.149.105 - - [02/Aug/2021 21:39:18] "GET /static/tools.js HTTP/1.1" 304 -
38.80.149.105 - - [02/Aug/2021 21:39:18] "GET /static/logo.png HTTP/1.1" 304 -
38.80.149.105 - - [02/Aug/2021 21:39:21] "POST /auth HTTP/1.1" 302 -
[2021-08-02 21:39:21,472] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "dashboard.py", line 485, in index
    return render_template('index.html', conf=get_conf_list())
  File "dashboard.py", line 268, in get_conf_list
    temp = {"conf": i, "status": get_conf_status(i), "public_key": get_conf_pub_key(i)}
  File "dashboard.py", line 255, in get_conf_status
    ifconfig = dict(ifcfg.interfaces().items())
  File "/usr/local/lib/python3.8/dist-packages/ifcfg/__init__.py", line 70, in interfaces
    return Parser(ifconfig=ifconfig).interfaces
  File "/usr/local/lib/python3.8/dist-packages/ifcfg/parser.py", line 30, in __init__
    self.parse(self.ifconfig_data)
  File "/usr/local/lib/python3.8/dist-packages/ifcfg/parser.py", line 90, in parse
    raise RuntimeError(
RuntimeError: Tried to add broadcast=0.0.0.0 multiple times to eth0, it was already: 0.0.0.0
38.80.149.105 - - [02/Aug/2021 21:39:21] "GET / HTTP/1.1" 500 -
38.80.149.105 - - [02/Aug/2021 21:39:21] "GET /favicon.ico HTTP/1.1" 404 -
```
**To Reproduce**
1. Start Server
2. Login

**OS Information:**
 - OS: Ubuntu 20.04
 - Python Version: 3.8.10

**Sample of your `.conf` file**
```
Please provide a sample of your configuration file that you are having problem with. You can replace your public key and private key to ABCD...
```

**Comment by donaldzou** [comment]
Could you provide a sample of your wg config?

**Comment by ben-dd** [comment]
For sure. What information are you looking for specifically? Obviously not going to post all my keys. hehe

**Comment by donaldzou** [comment]
I'm looking for the IPs you assigned to the peers, I don't need the keys, so you can just replace with `ABC1234` lol

**Comment by ben-dd** [comment]
```
# 10.8.0.0/24 fd42:42:42::0/64 0.0.0.0:51820 ABC123= 10.8.0.1,fd42:42:42:>
#
[Interface]
Address = 10.8.0.1/24,fd42:42:42::1/64
DNS = 10.8.0.1,fd42:42:42::1
ListenPort = 51820
MTU = 1280
PrivateKey = ABC123
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip6tables -A FOR>
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; ip6tables -D F>
SaveConfig = false
# BensMacBookPro start
[Peer]
PublicKey = ABC123
PresharedKey = ABC123
AllowedIPs = 10.8.0.3/32,fd42:42:42::3/128
# BensMacBookPro end
```

**Comment by donaldzou** [comment]
I think I know why, could you try to remove all comments, those starts with `#`, I'm still trying to figure out a way to compatible with comments, but for now comment in the `.conf` will bug out the dashboard ;)

**Comment by ben-dd** [comment]
Well, I seem to have deleted something I shouldn't have and I didn't make a backup of the file first... So I learned a tough lesson. I rebuilt my droplet and have Wireguard up and running. I'm going to forgo trying to use the dashboard for now. 

Thanks anyways.

**Comment by donaldzou** [comment]
Hi, I'm so sorry to hear this, but if there is anything I can help, please let me know.
