### ISSUE TITLE
No section: 'Interface' Error

### ISSUE THREAD

**Issue by ricohard** [donaldzou/wireguard-dashboard#53]
**A successful login returns the error:**

```
**Internal Server Error**

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Errors seen on the console:**

```
pi@wireguard:~/wireguard-dashboard/src $ ./wgd.sh debug
Starting Wireguard Dashboard in the foreground. 
 * Serving Flask app 'Wireguard Dashboard' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://192.168.1.6:10086/ (Press CTRL+C to quit)
192.168.1.117 - - [16/Aug/2021 22:01:07] "GET /signin HTTP/1.1" 200 -
192.168.1.117 - - [16/Aug/2021 22:01:07] "GET /static/js/jquery.min.js HTTP/1.1" 200 -
192.168.1.117 - - [16/Aug/2021 22:01:07] "GET /static/js/bootstrap.bundle.js HTTP/1.1" 200 -
192.168.1.117 - - [16/Aug/2021 22:01:07] "GET /static/css/dashboard.css HTTP/1.1" 200 -
192.168.1.117 - - [16/Aug/2021 22:01:07] "GET /static/js/tools.js HTTP/1.1" 200 -
192.168.1.117 - - [16/Aug/2021 22:01:11] "POST /auth HTTP/1.1" 302 -
[2021-08-16 22:01:11,370] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 676, in index
    return render_template('index.html', conf=get_conf_list())
  File "dashboard.py", line 308, in get_conf_list
    temp = {"conf": i, "status": get_conf_status(i), "public_key": get_conf_pub_key(i)}
  File "dashboard.py", line 264, in get_conf_pub_key
    pri = conf.get("Interface", "PrivateKey")
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Interface'
192.168.1.117 - - [16/Aug/2021 22:01:11] "GET / HTTP/1.1" 500 -
```

**wgd is started in the normal manner, nothing special**

`pi@wireguard:~/wireguard-dashboard/src $ ./wgd.sh debug`

or

`pi@wireguard:~/wireguard-dashboard/src $ ./wgd.sh start`

**Raspberry Pi 3b:**
```
pi@wireguard:~/wireguard-dashboard/src $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@wireguard:~/wireguard-dashboard/src $
```

```
pi@wireguard:~/wireguard-dashboard/src $ uname -a
Linux wireguard 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux
pi@wireguard:~/wireguard-dashboard/src $
```

**Sample of your `.conf` file**
```
[Interface]
Address = 192.168.99.1/24
ListenPort = 51820
PrivateKey = PRIVATEKEYHERE
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
SaveConfig = true

[Peer]
PublicKey = PUBLICKEY1
AllowedIPs = 192.168.99.2/32

[Peer]
PublicKey = PUBLICKEY2
AllowedIPs = 192.168.99.3/32

[Peer]
PublicKey = PUBLICKEY3
AllowedIPs = 192.168.99.4/32

[Peer]
PublicKey = PUBLICKEY4
AllowedIPs = 192.168.99.5/32

[Peer]
PublicKey= PUBLICKEY5
AllowedIPs = 192.168.99.6/32

[Peer]
PublicKey= PUBLICKEY6
AllowedIPs = 192.168.99.7/32

[Peer]
PublicKey= PUBLICKEY7
AllowedIPs = 192.168.99.8/32
```

I'd already read about issue #47 so this config has had all the comments removed but the commenting doesn't appear to make any difference to the error.

**Comment by donaldzou** [comment]
Hi, did you tried to run it with `sudo`? it might be some permission problem. Or is there a file under `/etc/wireguard` that ends with `.conf` but is a total different format inside, or is empty.

**Comment by ricohard** [comment]
sudo fails straight away:

```
pi@wireguard:~/wireguard-dashboard/src $ sudo ./wgd.sh debug
Starting Wireguard Dashboard in the foreground. 
Traceback (most recent call last):
  File "dashboard.py", line 15, in <module>
    import ifcfg
ModuleNotFoundError: No module named 'ifcfg'
pi@wireguard:~/wireguard-dashboard/src $
```

Maybe I need to run that requirements import as sudo...? I should try that.

The permissions, now they're interesting. Just looking at the files in /etc/wireguard gave me:

```
pi@wireguard:~ $ ls -l /etc/wireguard/
ls: cannot access '/etc/wireguard/wg0.conf': Permission denied
ls: cannot access '/etc/wireguard/wg0.conf.backup': Permission denied
total 0
-????????? ? ? ? ?            ? wg0.conf
-????????? ? ? ? ?            ? wg0.conf.backup
pi@wireguard:~ $
```

Now, that's not right. Digging deeper I can see this:

```
pi@wireguard:~ $ ls -ld /etc/wireguard/
drwxr--r-- 2 root root 4096 Aug 16 22:00 /etc/wireguard/
pi@wireguard:~ $
```

That's the change chmod 744 to the /etc/wireguard directory from 644. That did get me thinking though. With 744 the pi user can't actually read the contents of the directory (no permission for others to execute into the directory) which is probably why wgd thinks there is no "Interface" configuration.

Changing the permissions on /etc/wireguard to 755 actually works. 

```
pi@wireguard:~ $ ls -l /etc/wireguard/
total 8
-rw-r--r-- 1 root root 1062 Aug 16 22:00 wg0.conf
-rw-r--r-- 1 root root 1267 Aug 16 22:00 wg0.conf.backup
pi@wireguard:~ $
```

(The .backup file is the one with the peer comments in)

Brilliant. Sorted.

The line in the readme file saying to change the permission to 744 needs to change to 755 for it to work as a normal user on my Raspberry Pi. The question then though is: Is that secure? Probably not. I think it might be worth having a permissions check on /etc/wireguard to determine if the directory and contents can be read. If not, maybe, suggest a permissions change coupled with a warning that exposing the directory is a really bad idea. I'd help if I could but my python is barely beginner level...

I'll have to see if I can get this running under sudo now.

**Comment by donaldzou** [comment]
Hi, thank you very much on looking through all the settings, I will look for an alternative way, or a safer way to run the dashboard :)
