### ISSUE TITLE
Unterminated String / Invalid Control Character Breaks wgd.sh

### ISSUE THREAD

**Issue by reafian** [donaldzou/wireguard-dashboard#55]
**Describe The Problem**
Looking at a client configuration, I set a name and saved. This did not work.

**Expected Error / Traceback**

The initial error on the write
```
192.168.1.117 - - [17/Aug/2021 08:49:59] "GET /get_config/wg0?search= HTTP/1.1" 200 -
192.168.1.117 - - [17/Aug/2021 08:50:09] "POST /get_peer_data/wg0 HTTP/1.1" 200 -
192.168.1.117 - - [17/Aug/2021 08:50:16] "POST /save_peer_setting/wg0 HTTP/1.1" 200 -
[2021-08-17 08:50:16,419] ERROR in app: Exception on /get_config/wg0 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 715, in get_conf
    "peer_data": get_peers(config_name, search, sort),
  File "dashboard.py", line 248, in get_peers
    get_all_peers_data(config_name)
  File "dashboard.py", line 238, in get_all_peers_data
    get_latest_handshake(config_name, db, peers)
  File "dashboard.py", line 145, in get_latest_handshake
    db.update({"latest_handshake": "(None)", "status": status}, peers.id == data_usage[count])
  File "/usr/local/lib/python3.7/dist-packages/tinydb/table.py", line 370, in update
    self._update_table(updater)
  File "/usr/local/lib/python3.7/dist-packages/tinydb/table.py", line 672, in _update_table
    tables = self._storage.read()
  File "/usr/local/lib/python3.7/dist-packages/tinydb/storages.py", line 125, in read
    return json.load(self._handle)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2302 (char 2301)
192.168.1.117 - - [17/Aug/2021 08:50:16] "GET /get_config/wg0?search= HTTP/1.1" 500 -
```
Subsequent attempts to access wg0

```
192.168.1.117 - - [17/Aug/2021 08:50:16] "GET /get_config/wg0?search= HTTP/1.1" 500 -
[2021-08-17 08:50:29,496] ERROR in app: Exception on /get_config/wg0 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 715, in get_conf
    "peer_data": get_peers(config_name, search, sort),
  File "dashboard.py", line 248, in get_peers
    get_all_peers_data(config_name)
  File "dashboard.py", line 209, in get_all_peers_data
    search = db.search(peers.id == i['PublicKey'])
  File "/usr/local/lib/python3.7/dist-packages/tinydb/table.py", line 234, in search
    docs = [doc for doc in self if cond(doc)]
  File "/usr/local/lib/python3.7/dist-packages/tinydb/table.py", line 234, in <listcomp>
    docs = [doc for doc in self if cond(doc)]
  File "/usr/local/lib/python3.7/dist-packages/tinydb/table.py", line 588, in __iter__
    for doc_id, doc in self._read_table().items():
  File "/usr/local/lib/python3.7/dist-packages/tinydb/table.py", line 638, in _read_table
    tables = self._storage.read()
  File "/usr/local/lib/python3.7/dist-packages/tinydb/storages.py", line 125, in read
    return json.load(self._handle)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 2307 (char 2306)
192.168.1.117 - - [17/Aug/2021 08:50:29] "GET /get_config/wg0?search= HTTP/1.1" 500 -
```

**To Reproduce**
I just opened up a config (I was interested, and probably going to raise a ticket asking about, the lack of a private key and where / how the DNS entries) set a name and saved. Now the error appears in the logs and the wg0 page is empty. I'll need to re-install and try again to validate properly.

**OS Information:**
```
root@wireguard:~/wireguard-dashboard/src# cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@wireguard:~/wireguard-dashboard/src#

root@wireguard:~/wireguard-dashboard/src# uname -a
Linux wireguard 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux
root@wireguard:~/wireguard-dashboard/src#

root@wireguard:~/wireguard-dashboard/src# python3 --version
Python 3.7.3
root@wireguard:~/wireguard-dashboard/src#
```

**Sample of your `.conf` file**
This is my starting config. I didn't keep the written one. I'll try again later.
```
[Interface]
Address = 192.168.99.1/24
ListenPort = 51820
PrivateKey = PRIVATEKEY
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
SaveConfig = true

[Peer]
PublicKey = PUBLICKEY1
AllowedIPs = 192.168.99.2/32

[Peer]
PublicKey = PUBLICKEY2
AllowedIPs = 192.168.99.3/32

[Peer]
PublicKey = PUBLICKEY3
AllowedIPs = 192.168.99.4/32

[Peer]
PublicKey = PUBLICKEY4
AllowedIPs = 192.168.99.5/32

[Peer]
PublicKey= PUBLICKEY5
AllowedIPs = 192.168.99.6/32

[Peer]
PublicKey= PUBLICKEY6
AllowedIPs = 192.168.99.7/32

[Peer]
PublicKey= PUBLICKEY7
AllowedIPs = 192.168.99.8/32
root@wireguard:/etc/wireguard#
```

**Comment by ricohard** [comment]
This might have been a one-off error. Re-installing wgd from scratch seems to have worked and the error hasn't repeated. I use a wg0.conf file that had comments in and one that didn't. They both worked, although the one with comments in had the comments removed. I'd prefer to keep the comments but at least nothing broke.

I don't think I've done anything different so I don't really know why the error occurred. One to watch for.

**Comment by donaldzou** [comment]
Thank you for pointing out this, I might gonna make a general ticket for PI os, cuz I overcame many issue that is related to PI os.

**Comment by ricohard** [comment]
I'm happy to help where I can. The Raspberry Pi is my server and my clients are mostly Apple devices. I can always spin up a second server to play with if needed.

**Comment by donaldzou** [comment]
Thank you!!! I'll let you know if I need any help ;)
