### ISSUE TITLE
Limit access to dashboard with internal ip only 

### ISSUE THREAD

**Issue by donaldzou** [donaldzou/wireguard-dashboard#7]
Possible solution:
```
$ cd Wireguard-Dashboard/src
$ export FLASK_APP=dashboard.py
$ export FLASK_RUN_HOST= <The ip of your wireguard interface>
$ export FLASK_ENV=development
$ export FLASK_DEBUG=0
$ flask run
```

**Comment by teku45** [comment]
Am able to run the server internally on the computer I have dedicated as the WireGuard server with a few preconditions. I need to be as root user to run it. I have to set the environment variable `FLASK_RUN_HOST` equal to the IP I assigned my server. 

There are however some bugs in this format. I am able to start and run in production mode and access the landing page showing my 1 configuration (wg0), but when I click on it, It does not show me my peers anymore. This worked when I ran it publicly (not in the VPN) in non-production mode. 

when i click the wg0 configuration it takes me to a blank page and This error is thrown at me on the server:

```192.168.6.9 - - [06/Apr/2021 17:06:13] "GET /configuration/wg0 HTTP/1.1" 200 -
[2021-04-06 17:06:13,863] ERROR in app: Exception on /get_config/wg0 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lwaxana/Wireguard-Dashboard/src/dashboard.py", line 281, in get_conf
    "peer_data": getdb(config_name),
  File "/home/lwaxana/Wireguard-Dashboard/src/dashboard.py", line 169, in getdb
    get_conf_peers_data(config_name)
  File "/home/lwaxana/Wireguard-Dashboard/src/dashboard.py", line 93, in get_conf_peers_data
    if not db.search(peers.id == i):
  File "/usr/local/lib/python3.8/dist-packages/tinydb/table.py", line 233, in search
    docs = [doc for doc in self if cond(doc)]
  File "/usr/local/lib/python3.8/dist-packages/tinydb/table.py", line 233, in <listcomp>
    docs = [doc for doc in self if cond(doc)]
  File "/usr/local/lib/python3.8/dist-packages/tinydb/table.py", line 584, in __iter__
    for doc_id, doc in self._read_table().items():
  File "/usr/local/lib/python3.8/dist-packages/tinydb/table.py", line 634, in _read_table
    tables = self._storage.read()
  File "/usr/local/lib/python3.8/dist-packages/tinydb/storages.py", line 125, in read
    return json.load(self._handle)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 32419 (char 32418)
192.168.6.9 - - [06/Apr/2021 17:06:13] "GET /get_config/wg0 HTTP/1.1" 500 -```

**Comment by donaldzou** [comment]
@teku45 Hi could you provide what command you used? I changed my `FLASK_RUN_HOST=10.200.200.1` (that ip is my wg ip on my server) and have `flask run` and it only can be access thru connecting wireguard.

**Comment by teku45** [comment]
I used `flask run` as well and I used `FLASK_RUN_HOST=192.168.6.1` which is the IP of my server on the network

**Comment by donaldzou** [comment]
Hmmmm so every works well when you run publicly right, by using `python3 dashboard.py` ?

**Comment by donaldzou** [comment]
It looks like is something about the database. Can you try to remove the .json file under `wireguard-dashboard/src/json` that contained your wg conf's name? (i.e. `wg0`)
