### ISSUE TITLE
Feature request: Interface not loading when information missing

### ISSUE THREAD

**Issue by js32** [donaldzou/wireguard-dashboard#73]
**Describe The Problem**
I have a couple of pre-generated .conf-files from mullvad. They don‘t use „ListenPort“ but format the endpoints‘s IP like so: Address = 10.64.80.70:*5042*/32 and that prevents the dashboard from loading the interface information.

**To Reproduce**
Remove „Listenport“ from interface section of the config file.

**OS Information:**
 - OS: Ubuntu 20, happens on Dietpi 7.5.2 as well
 - Python Version: v3.7

**Sample of your `.conf` file**

```

[Interface]
PrivateKey = XXXX
Address = 10.64.80.70/32,fc00:bbbb:bbbb:bb01::1:5045/128
DNS = 193.138.218.74

[Peer]
PublicKey = YYYY
Endpoint = 193.32.249.66:51820
AllowedIPs = 0.0.0.0/0, ::/0

```

**Error Log**
```

Unable to access interface: No such device
Unable to access interface: No such device
Unable to access interface: No such device
[2021-09-05 19:52:07,190] ERROR in app: Exception on /get_config/mullvad-nl5 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'listenport'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/wireguard-dashboard/src/dashboard.py", line 734, in get_conf
    "listen_port": get_conf_listen_port(config_name),
  File "/opt/wireguard-dashboard/src/dashboard.py", line 283, in get_conf_listen_port
    port = conf.get("Interface", "ListenPort")
  File "/usr/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'listenport' in section: 'Interface'
192.168.178.47 - - [05/Sep/2021 19:52:07] "GET /get_config/mullvad-nl5?search= HTTP/1.1" 500 -

```

P.s.: The Dashboard also struggles with comments in the interface-file (e.g. „# some comment“).

**Comment by donaldzou** [comment]
Hi, this is because you did not specify a `listen_port` under `[Interface]` in your `.conf` file

**Comment by js32** [comment]
Hi,

yes, I know. I wanted to suggest that it would be good if Dashboard would just ignore those errors and display the interface anyway.

Dashboard even fails if an unexpected character is found, like a # for comments und the interface file.

**Comment by donaldzou** [comment]
Thank you for your suggestion! I will definitely fix this ;)
